version: "3"
services:
  bb3-ocpp-ws:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8060:8060

  tsdb:
    image: timescale/timescaledb:latest-pg13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=beepbeep3
      - TIMESCALEDB_TELEMETRY=off
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql:ro