version: "3"
services:
  nginx:
    image: nginx
    ports:
      - 8060:8060
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  ocpp-ws:
    build:
      context: .
      dockerfile: Dockerfile
