version: "3"
services:
  bb3-ocpp:
    build:
      context: .
      dockerfile: Dockerfile.bb3-ocpp
    ports:
      - 80:80
    env_file:
      - .env
    depends_on:
      - tsdb
    networks:
      - cgw

  tsdb:
    image: timescale/timescaledb:latest-pg13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=beep
      - POSTGRES_PASSWORD=beep
      - POSTGRES_DB=beepbeep3
      - TIMESCALEDB_TELEMETRY=off
    volumes:
      - ./migrations/postgres:/docker-entrypoint-initdb.d
    networks:
      - cgw

  pgweb:
    build:
      context: .
      dockerfile: Dockerfile.pgweb
    ports: 
      - 8062:8062
    environment:
      - PGWEB_PORT=8062
      - DATABASE_HOST=tsdb
      - DATABASE_PORT=5432
      - DATABASE_URL=postgres://beep:beep@tsdb:5432/beepbeep3?sslmode=disable
    depends_on:
      - tsdb
    networks:
      - cgw

networks:
  cgw:
    driver: bridge