// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"strconv"
	"time"

	"github.com/Beep-Technologies/beepbeep3-ocpp/pkg/constants"
)

// OcppTransaction is an object representing the database table.
type OcppTransaction struct {
	ID              int32     `gorm:"column:id"`
	ChargePointID   int32     `gorm:"column:charge_point_id"`
	ConnectorID     int32     `gorm:"column:connector_id"`
	IDTag           string    `gorm:"column:id_tag"`
	State           string    `gorm:"column:state"`
	RemoteInitiated bool      `gorm:"column:remote_initiated"`
	StartTimestamp  time.Time `gorm:"column:start_timestamp"`
	StopTimestamp   time.Time `gorm:"column:stop_timestamp"`
	StartMeterValue int32     `gorm:"column:start_meter_value"`
	StopMeterValue  int32     `gorm:"column:stop_meter_value"`
	StopReason      string    `gorm:"column:stop_reason"`
}

func (OcppTransaction) TableName() string {
	_ = strconv.Quote("")
	return constants.SCHEMA + "ocpp_transaction"
}
