// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"strconv"

	"github.com/Beep-Technologies/beepbeep3-iam/pkg/constants"
)

// OcppApplication is an object representing the database table.
type OcppApplication struct {
	ID   int32  `gorm:"column:id"`
	UUID string `gorm:"column:uuid"`
	Name string `gorm:"column:name"`
}

func (OcppApplication) TableName() string {
	_ = strconv.Quote("")
	return constants.SCHEMA + "ocpp_application"
}
