// Code generated by schema-generate. DO NOT EDIT.

package ocpp16

import (
    "bytes"
    "encoding/json"
    "fmt"
    "errors"
)

// HeartbeatResponse 
type HeartbeatResponse struct {
  CurrentTime string `json:"currentTime"`
}

func (strct *HeartbeatResponse) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "CurrentTime" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "currentTime" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"currentTime\": ")
	if tmp, err := json.Marshal(strct.CurrentTime); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *HeartbeatResponse) UnmarshalJSON(b []byte) error {
    currentTimeReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "currentTime":
            if err := json.Unmarshal([]byte(v), &strct.CurrentTime); err != nil {
                return err
             }
            currentTimeReceived = true
        default:
            return fmt.Errorf("additional property not allowed: \"" + k + "\"")
        }
    }
    // check if currentTime (a required property) was received
    if !currentTimeReceived {
        return errors.New("\"currentTime\" is required but was not present")
    }
    return nil
}
