// Code generated by schema-generate. DO NOT EDIT.

package ocpp16

import (
    "bytes"
    "encoding/json"
    "fmt"
    "errors"
)

// RemoteStopTransactionRequest 
type RemoteStopTransactionRequest struct {
  TransactionId int `json:"transactionId"`
}

func (strct *RemoteStopTransactionRequest) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "TransactionId" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "transactionId" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"transactionId\": ")
	if tmp, err := json.Marshal(strct.TransactionId); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *RemoteStopTransactionRequest) UnmarshalJSON(b []byte) error {
    transactionIdReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "transactionId":
            if err := json.Unmarshal([]byte(v), &strct.TransactionId); err != nil {
                return err
             }
            transactionIdReceived = true
        default:
            return fmt.Errorf("additional property not allowed: \"" + k + "\"")
        }
    }
    // check if transactionId (a required property) was received
    if !transactionIdReceived {
        return errors.New("\"transactionId\" is required but was not present")
    }
    return nil
}
