// Code generated by schema-generate. DO NOT EDIT.

package ocpp16

import (
    "errors"
    "bytes"
    "encoding/json"
    "fmt"
)

// ReserveNowRequest 
type ReserveNowRequest struct {
  ConnectorId int `json:"connectorId"`
  ExpiryDate string `json:"expiryDate"`
  IdTag string `json:"idTag"`
  ParentIdTag string `json:"parentIdTag,omitempty"`
  ReservationId int `json:"reservationId"`
}

func (strct *ReserveNowRequest) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "ConnectorId" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "connectorId" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"connectorId\": ")
	if tmp, err := json.Marshal(strct.ConnectorId); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "ExpiryDate" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "expiryDate" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"expiryDate\": ")
	if tmp, err := json.Marshal(strct.ExpiryDate); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "IdTag" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "idTag" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"idTag\": ")
	if tmp, err := json.Marshal(strct.IdTag); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "parentIdTag" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"parentIdTag\": ")
	if tmp, err := json.Marshal(strct.ParentIdTag); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "ReservationId" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "reservationId" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"reservationId\": ")
	if tmp, err := json.Marshal(strct.ReservationId); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *ReserveNowRequest) UnmarshalJSON(b []byte) error {
    connectorIdReceived := false
    expiryDateReceived := false
    idTagReceived := false
    reservationIdReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "connectorId":
            if err := json.Unmarshal([]byte(v), &strct.ConnectorId); err != nil {
                return err
             }
            connectorIdReceived = true
        case "expiryDate":
            if err := json.Unmarshal([]byte(v), &strct.ExpiryDate); err != nil {
                return err
             }
            expiryDateReceived = true
        case "idTag":
            if err := json.Unmarshal([]byte(v), &strct.IdTag); err != nil {
                return err
             }
            idTagReceived = true
        case "parentIdTag":
            if err := json.Unmarshal([]byte(v), &strct.ParentIdTag); err != nil {
                return err
             }
        case "reservationId":
            if err := json.Unmarshal([]byte(v), &strct.ReservationId); err != nil {
                return err
             }
            reservationIdReceived = true
        default:
            return fmt.Errorf("additional property not allowed: \"" + k + "\"")
        }
    }
    // check if connectorId (a required property) was received
    if !connectorIdReceived {
        return errors.New("\"connectorId\" is required but was not present")
    }
    // check if expiryDate (a required property) was received
    if !expiryDateReceived {
        return errors.New("\"expiryDate\" is required but was not present")
    }
    // check if idTag (a required property) was received
    if !idTagReceived {
        return errors.New("\"idTag\" is required but was not present")
    }
    // check if reservationId (a required property) was received
    if !reservationIdReceived {
        return errors.New("\"reservationId\" is required but was not present")
    }
    return nil
}
