// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: status_notifications.proto

package rpc

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StatusNotification struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	ConnectorId          int32    `protobuf:"varint,2,opt,name=connector_id,json=connectorId,proto3" json:"connector_id"`
	ErrorCode            string   `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code"`
	Info                 string   `protobuf:"bytes,4,opt,name=info,proto3" json:"info"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status"`
	VendorId             string   `protobuf:"bytes,6,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id"`
	VendorErrorCode      string   `protobuf:"bytes,7,opt,name=vendor_error_code,json=vendorErrorCode,proto3" json:"vendor_error_code"`
	Timestamp            string   `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp"`
	ReportedTimestamp    string   `protobuf:"bytes,9,opt,name=reported_timestamp,json=reportedTimestamp,proto3" json:"reported_timestamp"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusNotification) Reset()         { *m = StatusNotification{} }
func (m *StatusNotification) String() string { return proto.CompactTextString(m) }
func (*StatusNotification) ProtoMessage()    {}
func (*StatusNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ddc45ac0e19661, []int{0}
}
func (m *StatusNotification) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StatusNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StatusNotification.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StatusNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusNotification.Merge(m, src)
}
func (m *StatusNotification) XXX_Size() int {
	return m.Size()
}
func (m *StatusNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusNotification.DiscardUnknown(m)
}

var xxx_messageInfo_StatusNotification proto.InternalMessageInfo

type GetLatestStatusNotificationsReq struct {
	EntityCode            string   `protobuf:"bytes,1,opt,name=entity_code,json=entityCode,proto3" json:"entity_code,omitempty"`
	ChargePointIdentifier string   `protobuf:"bytes,2,opt,name=charge_point_identifier,json=chargePointIdentifier,proto3" json:"charge_point_identifier,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *GetLatestStatusNotificationsReq) Reset()         { *m = GetLatestStatusNotificationsReq{} }
func (m *GetLatestStatusNotificationsReq) String() string { return proto.CompactTextString(m) }
func (*GetLatestStatusNotificationsReq) ProtoMessage()    {}
func (*GetLatestStatusNotificationsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ddc45ac0e19661, []int{1}
}
func (m *GetLatestStatusNotificationsReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetLatestStatusNotificationsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetLatestStatusNotificationsReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetLatestStatusNotificationsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLatestStatusNotificationsReq.Merge(m, src)
}
func (m *GetLatestStatusNotificationsReq) XXX_Size() int {
	return m.Size()
}
func (m *GetLatestStatusNotificationsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLatestStatusNotificationsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetLatestStatusNotificationsReq proto.InternalMessageInfo

type GetLatestStatusNotificationsResp struct {
	ConnectorStatus      []*StatusNotification `protobuf:"bytes,1,rep,name=connector_status,json=connectorStatus,proto3" json:"connector_status"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetLatestStatusNotificationsResp) Reset()         { *m = GetLatestStatusNotificationsResp{} }
func (m *GetLatestStatusNotificationsResp) String() string { return proto.CompactTextString(m) }
func (*GetLatestStatusNotificationsResp) ProtoMessage()    {}
func (*GetLatestStatusNotificationsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ddc45ac0e19661, []int{2}
}
func (m *GetLatestStatusNotificationsResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetLatestStatusNotificationsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetLatestStatusNotificationsResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetLatestStatusNotificationsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLatestStatusNotificationsResp.Merge(m, src)
}
func (m *GetLatestStatusNotificationsResp) XXX_Size() int {
	return m.Size()
}
func (m *GetLatestStatusNotificationsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLatestStatusNotificationsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetLatestStatusNotificationsResp proto.InternalMessageInfo

type CreateStatusNotificationReq struct {
	EntityCode            string   `protobuf:"bytes,1,opt,name=entity_code,json=entityCode,proto3" json:"entity_code,omitempty"`
	ChargePointIdentifier string   `protobuf:"bytes,2,opt,name=charge_point_identifier,json=chargePointIdentifier,proto3" json:"charge_point_identifier,omitempty"`
	ConnectorId           int32    `protobuf:"varint,3,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`
	ErrorCode             string   `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Info                  string   `protobuf:"bytes,5,opt,name=info,proto3" json:"info,omitempty"`
	Status                string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp             string   `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	VendorId              string   `protobuf:"bytes,8,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	VendorErrorCode       string   `protobuf:"bytes,9,opt,name=vendor_error_code,json=vendorErrorCode,proto3" json:"vendor_error_code,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *CreateStatusNotificationReq) Reset()         { *m = CreateStatusNotificationReq{} }
func (m *CreateStatusNotificationReq) String() string { return proto.CompactTextString(m) }
func (*CreateStatusNotificationReq) ProtoMessage()    {}
func (*CreateStatusNotificationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ddc45ac0e19661, []int{3}
}
func (m *CreateStatusNotificationReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateStatusNotificationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateStatusNotificationReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateStatusNotificationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStatusNotificationReq.Merge(m, src)
}
func (m *CreateStatusNotificationReq) XXX_Size() int {
	return m.Size()
}
func (m *CreateStatusNotificationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStatusNotificationReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStatusNotificationReq proto.InternalMessageInfo

type CreateStatusNotificationResp struct {
	StatusNotification   *StatusNotification `protobuf:"bytes,1,opt,name=status_notification,json=statusNotification,proto3" json:"status_notification"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CreateStatusNotificationResp) Reset()         { *m = CreateStatusNotificationResp{} }
func (m *CreateStatusNotificationResp) String() string { return proto.CompactTextString(m) }
func (*CreateStatusNotificationResp) ProtoMessage()    {}
func (*CreateStatusNotificationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ddc45ac0e19661, []int{4}
}
func (m *CreateStatusNotificationResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateStatusNotificationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateStatusNotificationResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateStatusNotificationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStatusNotificationResp.Merge(m, src)
}
func (m *CreateStatusNotificationResp) XXX_Size() int {
	return m.Size()
}
func (m *CreateStatusNotificationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStatusNotificationResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStatusNotificationResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*StatusNotification)(nil), "ocpp.StatusNotification")
	proto.RegisterType((*GetLatestStatusNotificationsReq)(nil), "ocpp.GetLatestStatusNotificationsReq")
	proto.RegisterType((*GetLatestStatusNotificationsResp)(nil), "ocpp.GetLatestStatusNotificationsResp")
	proto.RegisterType((*CreateStatusNotificationReq)(nil), "ocpp.CreateStatusNotificationReq")
	proto.RegisterType((*CreateStatusNotificationResp)(nil), "ocpp.CreateStatusNotificationResp")
}

func init() { proto.RegisterFile("status_notifications.proto", fileDescriptor_a9ddc45ac0e19661) }

var fileDescriptor_a9ddc45ac0e19661 = []byte{
	// 614 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0xc7, 0xeb, 0xa4, 0x4d, 0xeb, 0xe9, 0xf7, 0xd1, 0x76, 0xa1, 0xad, 0x9b, 0x86, 0x6c, 0x6a,
	0x09, 0x14, 0x15, 0x35, 0x95, 0x5a, 0x89, 0x3b, 0xa9, 0x2a, 0x14, 0x09, 0x21, 0xb4, 0xe5, 0x02,
	0x17, 0xcb, 0xb1, 0x37, 0xe9, 0x1e, 0xe2, 0x35, 0xeb, 0x4d, 0x25, 0x90, 0xb8, 0xf0, 0x4e, 0xbc,
	0x43, 0x25, 0x2e, 0x3c, 0x81, 0x45, 0x73, 0x42, 0x3e, 0xf1, 0x08, 0x28, 0xbb, 0xae, 0xed, 0xe0,
	0x34, 0xe5, 0xc2, 0x25, 0xd9, 0xfd, 0xcf, 0xfc, 0xc7, 0xe3, 0x9d, 0x9f, 0x17, 0xea, 0x91, 0x74,
	0xe5, 0x38, 0x72, 0x02, 0x2e, 0xd9, 0x80, 0x79, 0xae, 0x64, 0x3c, 0x88, 0x3a, 0xa1, 0xe0, 0x92,
	0xa3, 0x65, 0xee, 0x85, 0x61, 0xfd, 0x68, 0xc8, 0xe4, 0xe5, 0xb8, 0xdf, 0xf1, 0xf8, 0xe8, 0x78,
	0xc8, 0x87, 0xfc, 0x58, 0x05, 0xfb, 0xe3, 0x81, 0xda, 0xa9, 0x8d, 0x5a, 0x69, 0x93, 0xfd, 0xb5,
	0x0a, 0xe8, 0x42, 0xd5, 0x7c, 0x5d, 0x28, 0x89, 0x76, 0xa0, 0xc2, 0x7c, 0xcb, 0x68, 0x19, 0xed,
	0x95, 0x6e, 0x2d, 0x89, 0x71, 0x85, 0xf9, 0xa4, 0xc2, 0x7c, 0x74, 0x0a, 0xff, 0x79, 0x3c, 0x08,
	0xa8, 0x27, 0xb9, 0x70, 0x98, 0x6f, 0x55, 0x54, 0xc6, 0x66, 0x12, 0xe3, 0x19, 0x9d, 0xac, 0x67,
	0xbb, 0x9e, 0x8f, 0x8e, 0x00, 0xa8, 0x10, 0x5c, 0x38, 0x1e, 0xf7, 0xa9, 0x55, 0x6d, 0x19, 0x6d,
	0xb3, 0xfb, 0x20, 0x89, 0x71, 0x41, 0x25, 0xa6, 0x5a, 0x9f, 0x71, 0x9f, 0xa2, 0x06, 0x2c, 0xb3,
	0x60, 0xc0, 0xad, 0x65, 0x95, 0xb8, 0x96, 0xc4, 0x58, 0xed, 0x89, 0xfa, 0x45, 0x36, 0xd4, 0xf4,
	0x19, 0x58, 0x2b, 0x2a, 0x0e, 0x49, 0x8c, 0x53, 0x85, 0xa4, 0xff, 0xe8, 0x10, 0xcc, 0x2b, 0x1a,
	0xf8, 0xba, 0xc5, 0x9a, 0x4a, 0xfb, 0x3f, 0x89, 0x71, 0x2e, 0x92, 0x35, 0xbd, 0xec, 0xf9, 0xe8,
	0x05, 0x6c, 0xa5, 0x72, 0xa1, 0xc7, 0x55, 0xe5, 0xd9, 0x4e, 0x62, 0x5c, 0x0e, 0x92, 0x0d, 0x2d,
	0x9d, 0x67, 0x0d, 0x3f, 0x03, 0x53, 0xb2, 0x11, 0x8d, 0xa4, 0x3b, 0x0a, 0xad, 0xb5, 0xfc, 0x71,
	0x99, 0x48, 0xf2, 0x25, 0x3a, 0x07, 0x24, 0x68, 0xc8, 0x85, 0xa4, 0xbe, 0x93, 0xbb, 0x4c, 0xe5,
	0xda, 0x49, 0x62, 0x3c, 0x27, 0x4a, 0xb6, 0x6e, 0xb5, 0xb7, 0xb7, 0x92, 0xfd, 0x09, 0xf0, 0x4b,
	0x2a, 0x5f, 0xb9, 0x92, 0x46, 0xb2, 0x3c, 0xbf, 0x88, 0xd0, 0x0f, 0x08, 0xc3, 0x3a, 0x0d, 0x24,
	0x93, 0x1f, 0xf5, 0x3b, 0x4d, 0x87, 0x69, 0x12, 0xd0, 0x92, 0xea, 0xfb, 0x39, 0xec, 0x7a, 0x97,
	0xae, 0x18, 0x52, 0x27, 0xe4, 0x2c, 0x90, 0x0e, 0xf3, 0xa7, 0xc1, 0x01, 0xa3, 0x42, 0xcd, 0xd5,
	0x24, 0xdb, 0x3a, 0xfc, 0x66, 0x1a, 0xed, 0x65, 0x41, 0xfb, 0x33, 0xb4, 0x16, 0x3f, 0x3b, 0x0a,
	0xd1, 0x3b, 0xd8, 0xcc, 0x81, 0x48, 0x07, 0x66, 0xb4, 0xaa, 0xed, 0xf5, 0x13, 0xab, 0x33, 0xe5,
	0xb4, 0x53, 0x36, 0x76, 0x1f, 0x25, 0x31, 0x2e, 0xb9, 0xc8, 0x46, 0xa6, 0x68, 0x8b, 0xfd, 0xad,
	0x02, 0xfb, 0x67, 0x82, 0xba, 0x92, 0x96, 0x6b, 0xfc, 0xcb, 0xf7, 0x46, 0x07, 0x7f, 0xc0, 0x3f,
	0x25, 0x79, 0x65, 0x16, 0xf5, 0xc7, 0x33, 0xa8, 0x2b, 0x82, 0x8b, 0x68, 0xa3, 0x14, 0x6d, 0x85,
	0x6e, 0x0a, 0xf4, 0x4e, 0x06, 0xb4, 0x22, 0x35, 0x83, 0xb8, 0x51, 0xa4, 0x6a, 0x55, 0x57, 0xca,
	0x31, 0xda, 0x2f, 0x22, 0xae, 0x98, 0x2b, 0x30, 0x7d, 0x38, 0x8f, 0x69, 0x85, 0x58, 0x09, 0x5e,
	0xfb, 0x8b, 0x01, 0x8d, 0xbb, 0x4f, 0x33, 0x0a, 0x51, 0x1f, 0x1e, 0xce, 0xb9, 0x74, 0xd4, 0xb1,
	0x2e, 0x1a, 0xe6, 0x6e, 0x12, 0xe3, 0x79, 0x46, 0x82, 0xa2, 0x52, 0xf2, 0xc9, 0x2f, 0x03, 0xf6,
	0xca, 0x35, 0x2e, 0xa8, 0xb8, 0x62, 0x1e, 0x45, 0x1c, 0x1a, 0x8b, 0x78, 0x43, 0x4f, 0x74, 0x13,
	0xf7, 0x7c, 0x0f, 0xf5, 0xa7, 0x7f, 0x93, 0x16, 0x85, 0xf6, 0x12, 0xea, 0x83, 0x75, 0xd7, 0x91,
	0xa0, 0x03, 0x5d, 0x65, 0x01, 0x80, 0xf5, 0xfb, 0x53, 0xec, 0xa5, 0xee, 0xde, 0xf5, 0x4d, 0x73,
	0xe9, 0xe7, 0x4d, 0xd3, 0xb8, 0x9e, 0x34, 0x8d, 0xef, 0x93, 0xa6, 0xf1, 0x63, 0xd2, 0x34, 0xde,
	0x57, 0x45, 0xe8, 0xf5, 0x6b, 0xea, 0x6a, 0x3e, 0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x70, 0xee,
	0x66, 0xd7, 0xed, 0x05, 0x00, 0x00,
}

type StatusNotificationFace interface {
	Proto() github_com_gogo_protobuf_proto.Message
	GetId() int32
	GetConnectorId() int32
	GetErrorCode() string
	GetInfo() string
	GetStatus() string
	GetVendorId() string
	GetVendorErrorCode() string
	GetTimestamp() string
	GetReportedTimestamp() string
}

func (this *StatusNotification) Proto() github_com_gogo_protobuf_proto.Message {
	return this
}

func (this *StatusNotification) TestProto() github_com_gogo_protobuf_proto.Message {
	return NewStatusNotificationFromFace(this)
}

func (this *StatusNotification) GetId() int32 {
	return this.Id
}

func (this *StatusNotification) GetConnectorId() int32 {
	return this.ConnectorId
}

func (this *StatusNotification) GetErrorCode() string {
	return this.ErrorCode
}

func (this *StatusNotification) GetInfo() string {
	return this.Info
}

func (this *StatusNotification) GetStatus() string {
	return this.Status
}

func (this *StatusNotification) GetVendorId() string {
	return this.VendorId
}

func (this *StatusNotification) GetVendorErrorCode() string {
	return this.VendorErrorCode
}

func (this *StatusNotification) GetTimestamp() string {
	return this.Timestamp
}

func (this *StatusNotification) GetReportedTimestamp() string {
	return this.ReportedTimestamp
}

func NewStatusNotificationFromFace(that StatusNotificationFace) *StatusNotification {
	this := &StatusNotification{}
	this.Id = that.GetId()
	this.ConnectorId = that.GetConnectorId()
	this.ErrorCode = that.GetErrorCode()
	this.Info = that.GetInfo()
	this.Status = that.GetStatus()
	this.VendorId = that.GetVendorId()
	this.VendorErrorCode = that.GetVendorErrorCode()
	this.Timestamp = that.GetTimestamp()
	this.ReportedTimestamp = that.GetReportedTimestamp()
	return this
}

type GetLatestStatusNotificationsReqFace interface {
	Proto() github_com_gogo_protobuf_proto.Message
	GetEntityCode() string
	GetChargePointIdentifier() string
}

func (this *GetLatestStatusNotificationsReq) Proto() github_com_gogo_protobuf_proto.Message {
	return this
}

func (this *GetLatestStatusNotificationsReq) TestProto() github_com_gogo_protobuf_proto.Message {
	return NewGetLatestStatusNotificationsReqFromFace(this)
}

func (this *GetLatestStatusNotificationsReq) GetEntityCode() string {
	return this.EntityCode
}

func (this *GetLatestStatusNotificationsReq) GetChargePointIdentifier() string {
	return this.ChargePointIdentifier
}

func NewGetLatestStatusNotificationsReqFromFace(that GetLatestStatusNotificationsReqFace) *GetLatestStatusNotificationsReq {
	this := &GetLatestStatusNotificationsReq{}
	this.EntityCode = that.GetEntityCode()
	this.ChargePointIdentifier = that.GetChargePointIdentifier()
	return this
}

type GetLatestStatusNotificationsRespFace interface {
	Proto() github_com_gogo_protobuf_proto.Message
	GetConnectorStatus() []*StatusNotification
}

func (this *GetLatestStatusNotificationsResp) Proto() github_com_gogo_protobuf_proto.Message {
	return this
}

func (this *GetLatestStatusNotificationsResp) TestProto() github_com_gogo_protobuf_proto.Message {
	return NewGetLatestStatusNotificationsRespFromFace(this)
}

func (this *GetLatestStatusNotificationsResp) GetConnectorStatus() []*StatusNotification {
	return this.ConnectorStatus
}

func NewGetLatestStatusNotificationsRespFromFace(that GetLatestStatusNotificationsRespFace) *GetLatestStatusNotificationsResp {
	this := &GetLatestStatusNotificationsResp{}
	this.ConnectorStatus = that.GetConnectorStatus()
	return this
}

type CreateStatusNotificationReqFace interface {
	Proto() github_com_gogo_protobuf_proto.Message
	GetEntityCode() string
	GetChargePointIdentifier() string
	GetConnectorId() int32
	GetErrorCode() string
	GetInfo() string
	GetStatus() string
	GetTimestamp() string
	GetVendorId() string
	GetVendorErrorCode() string
}

func (this *CreateStatusNotificationReq) Proto() github_com_gogo_protobuf_proto.Message {
	return this
}

func (this *CreateStatusNotificationReq) TestProto() github_com_gogo_protobuf_proto.Message {
	return NewCreateStatusNotificationReqFromFace(this)
}

func (this *CreateStatusNotificationReq) GetEntityCode() string {
	return this.EntityCode
}

func (this *CreateStatusNotificationReq) GetChargePointIdentifier() string {
	return this.ChargePointIdentifier
}

func (this *CreateStatusNotificationReq) GetConnectorId() int32 {
	return this.ConnectorId
}

func (this *CreateStatusNotificationReq) GetErrorCode() string {
	return this.ErrorCode
}

func (this *CreateStatusNotificationReq) GetInfo() string {
	return this.Info
}

func (this *CreateStatusNotificationReq) GetStatus() string {
	return this.Status
}

func (this *CreateStatusNotificationReq) GetTimestamp() string {
	return this.Timestamp
}

func (this *CreateStatusNotificationReq) GetVendorId() string {
	return this.VendorId
}

func (this *CreateStatusNotificationReq) GetVendorErrorCode() string {
	return this.VendorErrorCode
}

func NewCreateStatusNotificationReqFromFace(that CreateStatusNotificationReqFace) *CreateStatusNotificationReq {
	this := &CreateStatusNotificationReq{}
	this.EntityCode = that.GetEntityCode()
	this.ChargePointIdentifier = that.GetChargePointIdentifier()
	this.ConnectorId = that.GetConnectorId()
	this.ErrorCode = that.GetErrorCode()
	this.Info = that.GetInfo()
	this.Status = that.GetStatus()
	this.Timestamp = that.GetTimestamp()
	this.VendorId = that.GetVendorId()
	this.VendorErrorCode = that.GetVendorErrorCode()
	return this
}

type CreateStatusNotificationRespFace interface {
	Proto() github_com_gogo_protobuf_proto.Message
	GetStatusNotification() *StatusNotification
}

func (this *CreateStatusNotificationResp) Proto() github_com_gogo_protobuf_proto.Message {
	return this
}

func (this *CreateStatusNotificationResp) TestProto() github_com_gogo_protobuf_proto.Message {
	return NewCreateStatusNotificationRespFromFace(this)
}

func (this *CreateStatusNotificationResp) GetStatusNotification() *StatusNotification {
	return this.StatusNotification
}

func NewCreateStatusNotificationRespFromFace(that CreateStatusNotificationRespFace) *CreateStatusNotificationResp {
	this := &CreateStatusNotificationResp{}
	this.StatusNotification = that.GetStatusNotification()
	return this
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StatusNotificationServiceClient is the client API for StatusNotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatusNotificationServiceClient interface {
	GetLatestStatusNotifications(ctx context.Context, in *GetLatestStatusNotificationsReq, opts ...grpc.CallOption) (*GetLatestStatusNotificationsResp, error)
	CreateStatusNotification(ctx context.Context, in *CreateStatusNotificationReq, opts ...grpc.CallOption) (*CreateStatusNotificationReq, error)
}

type statusNotificationServiceClient struct {
	cc *grpc.ClientConn
}

func NewStatusNotificationServiceClient(cc *grpc.ClientConn) StatusNotificationServiceClient {
	return &statusNotificationServiceClient{cc}
}

func (c *statusNotificationServiceClient) GetLatestStatusNotifications(ctx context.Context, in *GetLatestStatusNotificationsReq, opts ...grpc.CallOption) (*GetLatestStatusNotificationsResp, error) {
	out := new(GetLatestStatusNotificationsResp)
	err := c.cc.Invoke(ctx, "/ocpp.StatusNotificationService/GetLatestStatusNotifications", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statusNotificationServiceClient) CreateStatusNotification(ctx context.Context, in *CreateStatusNotificationReq, opts ...grpc.CallOption) (*CreateStatusNotificationReq, error) {
	out := new(CreateStatusNotificationReq)
	err := c.cc.Invoke(ctx, "/ocpp.StatusNotificationService/CreateStatusNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatusNotificationServiceServer is the server API for StatusNotificationService service.
type StatusNotificationServiceServer interface {
	GetLatestStatusNotifications(context.Context, *GetLatestStatusNotificationsReq) (*GetLatestStatusNotificationsResp, error)
	CreateStatusNotification(context.Context, *CreateStatusNotificationReq) (*CreateStatusNotificationReq, error)
}

// UnimplementedStatusNotificationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStatusNotificationServiceServer struct {
}

func (*UnimplementedStatusNotificationServiceServer) GetLatestStatusNotifications(ctx context.Context, req *GetLatestStatusNotificationsReq) (*GetLatestStatusNotificationsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestStatusNotifications not implemented")
}
func (*UnimplementedStatusNotificationServiceServer) CreateStatusNotification(ctx context.Context, req *CreateStatusNotificationReq) (*CreateStatusNotificationReq, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStatusNotification not implemented")
}

func RegisterStatusNotificationServiceServer(s *grpc.Server, srv StatusNotificationServiceServer) {
	s.RegisterService(&_StatusNotificationService_serviceDesc, srv)
}

func _StatusNotificationService_GetLatestStatusNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestStatusNotificationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusNotificationServiceServer).GetLatestStatusNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ocpp.StatusNotificationService/GetLatestStatusNotifications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusNotificationServiceServer).GetLatestStatusNotifications(ctx, req.(*GetLatestStatusNotificationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatusNotificationService_CreateStatusNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStatusNotificationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusNotificationServiceServer).CreateStatusNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ocpp.StatusNotificationService/CreateStatusNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusNotificationServiceServer).CreateStatusNotification(ctx, req.(*CreateStatusNotificationReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _StatusNotificationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ocpp.StatusNotificationService",
	HandlerType: (*StatusNotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLatestStatusNotifications",
			Handler:    _StatusNotificationService_GetLatestStatusNotifications_Handler,
		},
		{
			MethodName: "CreateStatusNotification",
			Handler:    _StatusNotificationService_CreateStatusNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "status_notifications.proto",
}

func (m *StatusNotification) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StatusNotification) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StatusNotification) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.ReportedTimestamp) > 0 {
		i -= len(m.ReportedTimestamp)
		copy(dAtA[i:], m.ReportedTimestamp)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.ReportedTimestamp)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Timestamp) > 0 {
		i -= len(m.Timestamp)
		copy(dAtA[i:], m.Timestamp)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.Timestamp)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.VendorErrorCode) > 0 {
		i -= len(m.VendorErrorCode)
		copy(dAtA[i:], m.VendorErrorCode)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.VendorErrorCode)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.VendorId) > 0 {
		i -= len(m.VendorId)
		copy(dAtA[i:], m.VendorId)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.VendorId)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Info) > 0 {
		i -= len(m.Info)
		copy(dAtA[i:], m.Info)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.Info)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ErrorCode) > 0 {
		i -= len(m.ErrorCode)
		copy(dAtA[i:], m.ErrorCode)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.ErrorCode)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ConnectorId != 0 {
		i = encodeVarintStatusNotifications(dAtA, i, uint64(m.ConnectorId))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintStatusNotifications(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GetLatestStatusNotificationsReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLatestStatusNotificationsReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetLatestStatusNotificationsReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.ChargePointIdentifier) > 0 {
		i -= len(m.ChargePointIdentifier)
		copy(dAtA[i:], m.ChargePointIdentifier)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.ChargePointIdentifier)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.EntityCode) > 0 {
		i -= len(m.EntityCode)
		copy(dAtA[i:], m.EntityCode)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.EntityCode)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetLatestStatusNotificationsResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLatestStatusNotificationsResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetLatestStatusNotificationsResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.ConnectorStatus) > 0 {
		for iNdEx := len(m.ConnectorStatus) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ConnectorStatus[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintStatusNotifications(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *CreateStatusNotificationReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateStatusNotificationReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateStatusNotificationReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.VendorErrorCode) > 0 {
		i -= len(m.VendorErrorCode)
		copy(dAtA[i:], m.VendorErrorCode)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.VendorErrorCode)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.VendorId) > 0 {
		i -= len(m.VendorId)
		copy(dAtA[i:], m.VendorId)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.VendorId)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Timestamp) > 0 {
		i -= len(m.Timestamp)
		copy(dAtA[i:], m.Timestamp)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.Timestamp)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Info) > 0 {
		i -= len(m.Info)
		copy(dAtA[i:], m.Info)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.Info)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ErrorCode) > 0 {
		i -= len(m.ErrorCode)
		copy(dAtA[i:], m.ErrorCode)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.ErrorCode)))
		i--
		dAtA[i] = 0x22
	}
	if m.ConnectorId != 0 {
		i = encodeVarintStatusNotifications(dAtA, i, uint64(m.ConnectorId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ChargePointIdentifier) > 0 {
		i -= len(m.ChargePointIdentifier)
		copy(dAtA[i:], m.ChargePointIdentifier)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.ChargePointIdentifier)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.EntityCode) > 0 {
		i -= len(m.EntityCode)
		copy(dAtA[i:], m.EntityCode)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.EntityCode)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CreateStatusNotificationResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateStatusNotificationResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateStatusNotificationResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.StatusNotification != nil {
		{
			size, err := m.StatusNotification.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStatusNotifications(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintStatusNotifications(dAtA []byte, offset int, v uint64) int {
	offset -= sovStatusNotifications(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StatusNotification) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovStatusNotifications(uint64(m.Id))
	}
	if m.ConnectorId != 0 {
		n += 1 + sovStatusNotifications(uint64(m.ConnectorId))
	}
	l = len(m.ErrorCode)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	l = len(m.Info)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	l = len(m.VendorId)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	l = len(m.VendorErrorCode)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	l = len(m.Timestamp)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	l = len(m.ReportedTimestamp)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetLatestStatusNotificationsReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EntityCode)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	l = len(m.ChargePointIdentifier)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetLatestStatusNotificationsResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ConnectorStatus) > 0 {
		for _, e := range m.ConnectorStatus {
			l = e.Size()
			n += 1 + l + sovStatusNotifications(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *CreateStatusNotificationReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EntityCode)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	l = len(m.ChargePointIdentifier)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	if m.ConnectorId != 0 {
		n += 1 + sovStatusNotifications(uint64(m.ConnectorId))
	}
	l = len(m.ErrorCode)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	l = len(m.Info)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	l = len(m.Timestamp)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	l = len(m.VendorId)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	l = len(m.VendorErrorCode)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *CreateStatusNotificationResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StatusNotification != nil {
		l = m.StatusNotification.Size()
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovStatusNotifications(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStatusNotifications(x uint64) (n int) {
	return sovStatusNotifications(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StatusNotification) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStatusNotifications
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StatusNotification: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StatusNotification: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectorId", wireType)
			}
			m.ConnectorId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConnectorId |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrorCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Info = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VendorId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VendorId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VendorErrorCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VendorErrorCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Timestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReportedTimestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReportedTimestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStatusNotifications(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLatestStatusNotificationsReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStatusNotifications
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLatestStatusNotificationsReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLatestStatusNotificationsReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EntityCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EntityCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChargePointIdentifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChargePointIdentifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStatusNotifications(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLatestStatusNotificationsResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStatusNotifications
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLatestStatusNotificationsResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLatestStatusNotificationsResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectorStatus", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConnectorStatus = append(m.ConnectorStatus, &StatusNotification{})
			if err := m.ConnectorStatus[len(m.ConnectorStatus)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStatusNotifications(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateStatusNotificationReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStatusNotifications
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateStatusNotificationReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateStatusNotificationReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EntityCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EntityCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChargePointIdentifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChargePointIdentifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectorId", wireType)
			}
			m.ConnectorId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConnectorId |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrorCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Info = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Timestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VendorId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VendorId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VendorErrorCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VendorErrorCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStatusNotifications(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateStatusNotificationResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStatusNotifications
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateStatusNotificationResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateStatusNotificationResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusNotification", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StatusNotification == nil {
				m.StatusNotification = &StatusNotification{}
			}
			if err := m.StatusNotification.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStatusNotifications(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStatusNotifications(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStatusNotifications
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStatusNotifications
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStatusNotifications
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStatusNotifications
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStatusNotifications        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStatusNotifications          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStatusNotifications = fmt.Errorf("proto: unexpected end of group")
)
