// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: status_notifications.proto

package rpc

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StatusNotification struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	ChargePointId        int32    `protobuf:"varint,2,opt,name=charge_point_id,json=chargePointId,proto3" json:"charge_point_id"`
	ConnectorId          int32    `protobuf:"varint,3,opt,name=connector_id,json=connectorId,proto3" json:"connector_id"`
	ErrorCode            string   `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code"`
	Info                 string   `protobuf:"bytes,5,opt,name=info,proto3" json:"info"`
	Status               string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status"`
	VendorId             string   `protobuf:"bytes,7,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id"`
	VendorErrorCode      string   `protobuf:"bytes,8,opt,name=vendor_error_code,json=vendorErrorCode,proto3" json:"vendor_error_code"`
	Timestamp            string   `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp"`
	ReportedTimestamp    string   `protobuf:"bytes,10,opt,name=reported_timestamp,json=reportedTimestamp,proto3" json:"reported_timestamp"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusNotification) Reset()         { *m = StatusNotification{} }
func (m *StatusNotification) String() string { return proto.CompactTextString(m) }
func (*StatusNotification) ProtoMessage()    {}
func (*StatusNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ddc45ac0e19661, []int{0}
}
func (m *StatusNotification) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StatusNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StatusNotification.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StatusNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusNotification.Merge(m, src)
}
func (m *StatusNotification) XXX_Size() int {
	return m.Size()
}
func (m *StatusNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusNotification.DiscardUnknown(m)
}

var xxx_messageInfo_StatusNotification proto.InternalMessageInfo

// for exposed services
type GetLatestStatusNotificationsReq struct {
	ApplicationId         int32    `protobuf:"varint,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	ChargePointIdentifier string   `protobuf:"bytes,2,opt,name=charge_point_identifier,json=chargePointIdentifier,proto3" json:"charge_point_identifier,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *GetLatestStatusNotificationsReq) Reset()         { *m = GetLatestStatusNotificationsReq{} }
func (m *GetLatestStatusNotificationsReq) String() string { return proto.CompactTextString(m) }
func (*GetLatestStatusNotificationsReq) ProtoMessage()    {}
func (*GetLatestStatusNotificationsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ddc45ac0e19661, []int{1}
}
func (m *GetLatestStatusNotificationsReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetLatestStatusNotificationsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetLatestStatusNotificationsReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetLatestStatusNotificationsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLatestStatusNotificationsReq.Merge(m, src)
}
func (m *GetLatestStatusNotificationsReq) XXX_Size() int {
	return m.Size()
}
func (m *GetLatestStatusNotificationsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLatestStatusNotificationsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetLatestStatusNotificationsReq proto.InternalMessageInfo

type GetLatestStatusNotificationsResp struct {
	ConnectorStatus      []*StatusNotification `protobuf:"bytes,1,rep,name=connector_status,json=connectorStatus,proto3" json:"connector_status"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetLatestStatusNotificationsResp) Reset()         { *m = GetLatestStatusNotificationsResp{} }
func (m *GetLatestStatusNotificationsResp) String() string { return proto.CompactTextString(m) }
func (*GetLatestStatusNotificationsResp) ProtoMessage()    {}
func (*GetLatestStatusNotificationsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ddc45ac0e19661, []int{2}
}
func (m *GetLatestStatusNotificationsResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetLatestStatusNotificationsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetLatestStatusNotificationsResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetLatestStatusNotificationsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLatestStatusNotificationsResp.Merge(m, src)
}
func (m *GetLatestStatusNotificationsResp) XXX_Size() int {
	return m.Size()
}
func (m *GetLatestStatusNotificationsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLatestStatusNotificationsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetLatestStatusNotificationsResp proto.InternalMessageInfo

// for internal services
type CreateStatusNotificationReq struct {
	ApplicationId        int32    `protobuf:"varint,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	ChargePointId        int32    `protobuf:"varint,2,opt,name=charge_point_id,json=chargePointId,proto3" json:"charge_point_id,omitempty"`
	ConnectorId          int32    `protobuf:"varint,3,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`
	ErrorCode            string   `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Info                 string   `protobuf:"bytes,5,opt,name=info,proto3" json:"info,omitempty"`
	Status               string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp            string   `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	VendorId             string   `protobuf:"bytes,8,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	VendorErrorCode      string   `protobuf:"bytes,9,opt,name=vendor_error_code,json=vendorErrorCode,proto3" json:"vendor_error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStatusNotificationReq) Reset()         { *m = CreateStatusNotificationReq{} }
func (m *CreateStatusNotificationReq) String() string { return proto.CompactTextString(m) }
func (*CreateStatusNotificationReq) ProtoMessage()    {}
func (*CreateStatusNotificationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ddc45ac0e19661, []int{3}
}
func (m *CreateStatusNotificationReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateStatusNotificationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateStatusNotificationReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateStatusNotificationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStatusNotificationReq.Merge(m, src)
}
func (m *CreateStatusNotificationReq) XXX_Size() int {
	return m.Size()
}
func (m *CreateStatusNotificationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStatusNotificationReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStatusNotificationReq proto.InternalMessageInfo

type CreateStatusNotificationResp struct {
	StatusNotification   *StatusNotification `protobuf:"bytes,1,opt,name=status_notification,json=statusNotification,proto3" json:"status_notification"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CreateStatusNotificationResp) Reset()         { *m = CreateStatusNotificationResp{} }
func (m *CreateStatusNotificationResp) String() string { return proto.CompactTextString(m) }
func (*CreateStatusNotificationResp) ProtoMessage()    {}
func (*CreateStatusNotificationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ddc45ac0e19661, []int{4}
}
func (m *CreateStatusNotificationResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateStatusNotificationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateStatusNotificationResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateStatusNotificationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStatusNotificationResp.Merge(m, src)
}
func (m *CreateStatusNotificationResp) XXX_Size() int {
	return m.Size()
}
func (m *CreateStatusNotificationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStatusNotificationResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStatusNotificationResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*StatusNotification)(nil), "ocpp.StatusNotification")
	proto.RegisterType((*GetLatestStatusNotificationsReq)(nil), "ocpp.GetLatestStatusNotificationsReq")
	proto.RegisterType((*GetLatestStatusNotificationsResp)(nil), "ocpp.GetLatestStatusNotificationsResp")
	proto.RegisterType((*CreateStatusNotificationReq)(nil), "ocpp.CreateStatusNotificationReq")
	proto.RegisterType((*CreateStatusNotificationResp)(nil), "ocpp.CreateStatusNotificationResp")
}

func init() { proto.RegisterFile("status_notifications.proto", fileDescriptor_a9ddc45ac0e19661) }

var fileDescriptor_a9ddc45ac0e19661 = []byte{
	// 576 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x71, 0xd2, 0xa6, 0xf1, 0x94, 0x34, 0xed, 0x96, 0xa6, 0xa6, 0x0d, 0xd9, 0x60, 0x09,
	0x14, 0x15, 0x35, 0x95, 0xa8, 0xc4, 0x85, 0x13, 0xa9, 0x2a, 0x14, 0x09, 0x21, 0xb4, 0x70, 0x81,
	0x8b, 0xe5, 0x78, 0x37, 0xa9, 0x25, 0xe2, 0x35, 0xf6, 0x86, 0x1b, 0x12, 0xe2, 0xcd, 0xb8, 0xf5,
	0xc8, 0x13, 0xac, 0x68, 0x4e, 0x68, 0x8f, 0x3c, 0x01, 0xca, 0xda, 0x89, 0x9d, 0x38, 0xad, 0xc4,
	0x25, 0xd9, 0xf9, 0x67, 0xfe, 0xc9, 0x64, 0xe7, 0xb3, 0xe1, 0x28, 0x16, 0xae, 0x98, 0xc4, 0x4e,
	0xc0, 0x85, 0x3f, 0xf4, 0x3d, 0x57, 0xf8, 0x3c, 0x88, 0xbb, 0x61, 0xc4, 0x05, 0x47, 0x1b, 0xdc,
	0x0b, 0xc3, 0xa3, 0xd3, 0x91, 0x2f, 0xae, 0x26, 0x83, 0xae, 0xc7, 0xc7, 0x67, 0x23, 0x3e, 0xe2,
	0x67, 0x3a, 0x39, 0x98, 0x0c, 0x75, 0xa4, 0x03, 0x7d, 0x4a, 0x4c, 0xf6, 0xdf, 0x32, 0xa0, 0xf7,
	0xba, 0xe7, 0xdb, 0x5c, 0x4b, 0xd4, 0x80, 0x92, 0x4f, 0x2d, 0xa3, 0x6d, 0x74, 0x36, 0x7b, 0x15,
	0x25, 0x71, 0xc9, 0xa7, 0xa4, 0xe4, 0x53, 0xf4, 0x12, 0xea, 0xde, 0x95, 0x1b, 0x8d, 0x98, 0x13,
	0x72, 0x3f, 0x10, 0x8e, 0x4f, 0xad, 0x92, 0x2e, 0xda, 0x57, 0x12, 0xaf, 0xa6, 0x48, 0x2d, 0x11,
	0xde, 0xcd, 0xe2, 0x3e, 0x45, 0xe7, 0x70, 0xdf, 0xe3, 0x41, 0xc0, 0x3c, 0xc1, 0xa3, 0x99, 0xb3,
	0xac, 0x9d, 0xbb, 0x4a, 0xe2, 0x25, 0x9d, 0x6c, 0x2f, 0xa2, 0x3e, 0x45, 0xa7, 0x00, 0x2c, 0x8a,
	0x78, 0xe4, 0x78, 0x9c, 0x32, 0x6b, 0xa3, 0x6d, 0x74, 0xcc, 0xde, 0x8e, 0x92, 0x38, 0xa7, 0x12,
	0x53, 0x9f, 0x2f, 0x38, 0x65, 0xa8, 0x09, 0x1b, 0x7e, 0x30, 0xe4, 0xd6, 0xa6, 0x2e, 0xac, 0x2a,
	0x89, 0x75, 0x4c, 0xf4, 0x27, 0xb2, 0xa1, 0x92, 0x5c, 0xa0, 0x55, 0xd1, 0x79, 0x50, 0x12, 0xa7,
	0x0a, 0x49, 0xbf, 0xd1, 0x09, 0x98, 0x5f, 0x59, 0x40, 0x93, 0x11, 0xb7, 0x74, 0x59, 0x4d, 0x49,
	0x9c, 0x89, 0xa4, 0x9a, 0x1c, 0xfb, 0x14, 0xbd, 0x82, 0xbd, 0x54, 0xce, 0xcd, 0x58, 0xd5, 0x9e,
	0x03, 0x25, 0x71, 0x31, 0x49, 0xea, 0x89, 0x74, 0xb9, 0x18, 0xf8, 0x19, 0x98, 0xc2, 0x1f, 0xb3,
	0x58, 0xb8, 0xe3, 0xd0, 0x32, 0xb3, 0x9f, 0x5b, 0x88, 0x24, 0x3b, 0xa2, 0x4b, 0x40, 0x11, 0x0b,
	0x79, 0x24, 0x18, 0x75, 0x32, 0x17, 0x68, 0x57, 0x43, 0x49, 0xbc, 0x26, 0x4b, 0xf6, 0xe6, 0xda,
	0x87, 0xb9, 0x64, 0x7f, 0x37, 0x00, 0xbf, 0x66, 0xe2, 0x8d, 0x2b, 0x58, 0x2c, 0x8a, 0xdb, 0x8f,
	0x09, 0xfb, 0x82, 0x9e, 0xc0, 0x8e, 0x1b, 0x86, 0x9f, 0x53, 0xc9, 0x99, 0xd3, 0x40, 0x6a, 0x39,
	0xb5, 0x4f, 0xd1, 0x0b, 0x38, 0x5c, 0xd9, 0x3a, 0x0b, 0x66, 0x9d, 0x58, 0xa4, 0xc1, 0x30, 0xc9,
	0xc1, 0x12, 0x03, 0xf3, 0xa4, 0xfd, 0x0d, 0xda, 0x77, 0x4f, 0x10, 0x87, 0xe8, 0x23, 0xec, 0x66,
	0x5c, 0xa4, 0x7b, 0x33, 0xda, 0xe5, 0xce, 0xf6, 0x73, 0xab, 0x3b, 0x63, 0xbd, 0x5b, 0x34, 0xf6,
	0x1e, 0x28, 0x89, 0x0b, 0x2e, 0x52, 0x5f, 0x28, 0x89, 0xc5, 0xfe, 0x59, 0x82, 0xe3, 0x8b, 0x88,
	0xb9, 0x82, 0x15, 0x7b, 0xfc, 0xc7, 0xbf, 0x7f, 0x7a, 0xcb, 0xe3, 0xb0, 0x4a, 0xfe, 0xe3, 0x75,
	0xe4, 0x2f, 0x73, 0xfe, 0xa8, 0xc8, 0x79, 0x9e, 0x6b, 0x94, 0xe7, 0x3a, 0xa5, 0xb9, 0xb1, 0x4c,
	0xf3, 0x82, 0xe0, 0x66, 0x1e, 0xa9, 0xad, 0xa4, 0x53, 0xc6, 0xd0, 0x71, 0x9e, 0x6f, 0xcd, 0x6a,
	0x0e, 0xe8, 0x93, 0x75, 0x40, 0x6b, 0x2a, 0x0b, 0xe4, 0xda, 0x3f, 0x0c, 0x68, 0xde, 0x7e, 0x87,
	0x71, 0x88, 0x06, 0xb0, 0xbf, 0xe6, 0x75, 0xa5, 0x6f, 0xf2, 0xae, 0x15, 0x1e, 0x2a, 0x89, 0xd7,
	0x19, 0x09, 0x8a, 0x8b, 0xc5, 0x0f, 0xaf, 0x6f, 0x5a, 0xf7, 0xfe, 0xdc, 0xb4, 0x8c, 0xeb, 0x69,
	0xcb, 0xf8, 0x35, 0x6d, 0x19, 0xbf, 0xa7, 0x2d, 0xe3, 0x53, 0x39, 0x0a, 0xbd, 0x41, 0x45, 0xbf,
	0xe1, 0xce, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x29, 0x25, 0xa4, 0x78, 0x34, 0x05, 0x00, 0x00,
}

type StatusNotificationFace interface {
	Proto() github_com_gogo_protobuf_proto.Message
	GetId() int32
	GetChargePointId() int32
	GetConnectorId() int32
	GetErrorCode() string
	GetInfo() string
	GetStatus() string
	GetVendorId() string
	GetVendorErrorCode() string
	GetTimestamp() string
	GetReportedTimestamp() string
}

func (this *StatusNotification) Proto() github_com_gogo_protobuf_proto.Message {
	return this
}

func (this *StatusNotification) TestProto() github_com_gogo_protobuf_proto.Message {
	return NewStatusNotificationFromFace(this)
}

func (this *StatusNotification) GetId() int32 {
	return this.Id
}

func (this *StatusNotification) GetChargePointId() int32 {
	return this.ChargePointId
}

func (this *StatusNotification) GetConnectorId() int32 {
	return this.ConnectorId
}

func (this *StatusNotification) GetErrorCode() string {
	return this.ErrorCode
}

func (this *StatusNotification) GetInfo() string {
	return this.Info
}

func (this *StatusNotification) GetStatus() string {
	return this.Status
}

func (this *StatusNotification) GetVendorId() string {
	return this.VendorId
}

func (this *StatusNotification) GetVendorErrorCode() string {
	return this.VendorErrorCode
}

func (this *StatusNotification) GetTimestamp() string {
	return this.Timestamp
}

func (this *StatusNotification) GetReportedTimestamp() string {
	return this.ReportedTimestamp
}

func NewStatusNotificationFromFace(that StatusNotificationFace) *StatusNotification {
	this := &StatusNotification{}
	this.Id = that.GetId()
	this.ChargePointId = that.GetChargePointId()
	this.ConnectorId = that.GetConnectorId()
	this.ErrorCode = that.GetErrorCode()
	this.Info = that.GetInfo()
	this.Status = that.GetStatus()
	this.VendorId = that.GetVendorId()
	this.VendorErrorCode = that.GetVendorErrorCode()
	this.Timestamp = that.GetTimestamp()
	this.ReportedTimestamp = that.GetReportedTimestamp()
	return this
}

type GetLatestStatusNotificationsReqFace interface {
	Proto() github_com_gogo_protobuf_proto.Message
	GetApplicationId() int32
	GetChargePointIdentifier() string
}

func (this *GetLatestStatusNotificationsReq) Proto() github_com_gogo_protobuf_proto.Message {
	return this
}

func (this *GetLatestStatusNotificationsReq) TestProto() github_com_gogo_protobuf_proto.Message {
	return NewGetLatestStatusNotificationsReqFromFace(this)
}

func (this *GetLatestStatusNotificationsReq) GetApplicationId() int32 {
	return this.ApplicationId
}

func (this *GetLatestStatusNotificationsReq) GetChargePointIdentifier() string {
	return this.ChargePointIdentifier
}

func NewGetLatestStatusNotificationsReqFromFace(that GetLatestStatusNotificationsReqFace) *GetLatestStatusNotificationsReq {
	this := &GetLatestStatusNotificationsReq{}
	this.ApplicationId = that.GetApplicationId()
	this.ChargePointIdentifier = that.GetChargePointIdentifier()
	return this
}

type GetLatestStatusNotificationsRespFace interface {
	Proto() github_com_gogo_protobuf_proto.Message
	GetConnectorStatus() []*StatusNotification
}

func (this *GetLatestStatusNotificationsResp) Proto() github_com_gogo_protobuf_proto.Message {
	return this
}

func (this *GetLatestStatusNotificationsResp) TestProto() github_com_gogo_protobuf_proto.Message {
	return NewGetLatestStatusNotificationsRespFromFace(this)
}

func (this *GetLatestStatusNotificationsResp) GetConnectorStatus() []*StatusNotification {
	return this.ConnectorStatus
}

func NewGetLatestStatusNotificationsRespFromFace(that GetLatestStatusNotificationsRespFace) *GetLatestStatusNotificationsResp {
	this := &GetLatestStatusNotificationsResp{}
	this.ConnectorStatus = that.GetConnectorStatus()
	return this
}

type CreateStatusNotificationReqFace interface {
	Proto() github_com_gogo_protobuf_proto.Message
	GetApplicationId() int32
	GetChargePointId() int32
	GetConnectorId() int32
	GetErrorCode() string
	GetInfo() string
	GetStatus() string
	GetTimestamp() string
	GetVendorId() string
	GetVendorErrorCode() string
}

func (this *CreateStatusNotificationReq) Proto() github_com_gogo_protobuf_proto.Message {
	return this
}

func (this *CreateStatusNotificationReq) TestProto() github_com_gogo_protobuf_proto.Message {
	return NewCreateStatusNotificationReqFromFace(this)
}

func (this *CreateStatusNotificationReq) GetApplicationId() int32 {
	return this.ApplicationId
}

func (this *CreateStatusNotificationReq) GetChargePointId() int32 {
	return this.ChargePointId
}

func (this *CreateStatusNotificationReq) GetConnectorId() int32 {
	return this.ConnectorId
}

func (this *CreateStatusNotificationReq) GetErrorCode() string {
	return this.ErrorCode
}

func (this *CreateStatusNotificationReq) GetInfo() string {
	return this.Info
}

func (this *CreateStatusNotificationReq) GetStatus() string {
	return this.Status
}

func (this *CreateStatusNotificationReq) GetTimestamp() string {
	return this.Timestamp
}

func (this *CreateStatusNotificationReq) GetVendorId() string {
	return this.VendorId
}

func (this *CreateStatusNotificationReq) GetVendorErrorCode() string {
	return this.VendorErrorCode
}

func NewCreateStatusNotificationReqFromFace(that CreateStatusNotificationReqFace) *CreateStatusNotificationReq {
	this := &CreateStatusNotificationReq{}
	this.ApplicationId = that.GetApplicationId()
	this.ChargePointId = that.GetChargePointId()
	this.ConnectorId = that.GetConnectorId()
	this.ErrorCode = that.GetErrorCode()
	this.Info = that.GetInfo()
	this.Status = that.GetStatus()
	this.Timestamp = that.GetTimestamp()
	this.VendorId = that.GetVendorId()
	this.VendorErrorCode = that.GetVendorErrorCode()
	return this
}

type CreateStatusNotificationRespFace interface {
	Proto() github_com_gogo_protobuf_proto.Message
	GetStatusNotification() *StatusNotification
}

func (this *CreateStatusNotificationResp) Proto() github_com_gogo_protobuf_proto.Message {
	return this
}

func (this *CreateStatusNotificationResp) TestProto() github_com_gogo_protobuf_proto.Message {
	return NewCreateStatusNotificationRespFromFace(this)
}

func (this *CreateStatusNotificationResp) GetStatusNotification() *StatusNotification {
	return this.StatusNotification
}

func NewCreateStatusNotificationRespFromFace(that CreateStatusNotificationRespFace) *CreateStatusNotificationResp {
	this := &CreateStatusNotificationResp{}
	this.StatusNotification = that.GetStatusNotification()
	return this
}

func (m *StatusNotification) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StatusNotification) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StatusNotification) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.ReportedTimestamp) > 0 {
		i -= len(m.ReportedTimestamp)
		copy(dAtA[i:], m.ReportedTimestamp)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.ReportedTimestamp)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Timestamp) > 0 {
		i -= len(m.Timestamp)
		copy(dAtA[i:], m.Timestamp)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.Timestamp)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.VendorErrorCode) > 0 {
		i -= len(m.VendorErrorCode)
		copy(dAtA[i:], m.VendorErrorCode)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.VendorErrorCode)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.VendorId) > 0 {
		i -= len(m.VendorId)
		copy(dAtA[i:], m.VendorId)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.VendorId)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Info) > 0 {
		i -= len(m.Info)
		copy(dAtA[i:], m.Info)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.Info)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ErrorCode) > 0 {
		i -= len(m.ErrorCode)
		copy(dAtA[i:], m.ErrorCode)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.ErrorCode)))
		i--
		dAtA[i] = 0x22
	}
	if m.ConnectorId != 0 {
		i = encodeVarintStatusNotifications(dAtA, i, uint64(m.ConnectorId))
		i--
		dAtA[i] = 0x18
	}
	if m.ChargePointId != 0 {
		i = encodeVarintStatusNotifications(dAtA, i, uint64(m.ChargePointId))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintStatusNotifications(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GetLatestStatusNotificationsReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLatestStatusNotificationsReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetLatestStatusNotificationsReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.ChargePointIdentifier) > 0 {
		i -= len(m.ChargePointIdentifier)
		copy(dAtA[i:], m.ChargePointIdentifier)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.ChargePointIdentifier)))
		i--
		dAtA[i] = 0x12
	}
	if m.ApplicationId != 0 {
		i = encodeVarintStatusNotifications(dAtA, i, uint64(m.ApplicationId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GetLatestStatusNotificationsResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLatestStatusNotificationsResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetLatestStatusNotificationsResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.ConnectorStatus) > 0 {
		for iNdEx := len(m.ConnectorStatus) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ConnectorStatus[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintStatusNotifications(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *CreateStatusNotificationReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateStatusNotificationReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateStatusNotificationReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.VendorErrorCode) > 0 {
		i -= len(m.VendorErrorCode)
		copy(dAtA[i:], m.VendorErrorCode)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.VendorErrorCode)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.VendorId) > 0 {
		i -= len(m.VendorId)
		copy(dAtA[i:], m.VendorId)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.VendorId)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Timestamp) > 0 {
		i -= len(m.Timestamp)
		copy(dAtA[i:], m.Timestamp)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.Timestamp)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Info) > 0 {
		i -= len(m.Info)
		copy(dAtA[i:], m.Info)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.Info)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ErrorCode) > 0 {
		i -= len(m.ErrorCode)
		copy(dAtA[i:], m.ErrorCode)
		i = encodeVarintStatusNotifications(dAtA, i, uint64(len(m.ErrorCode)))
		i--
		dAtA[i] = 0x22
	}
	if m.ConnectorId != 0 {
		i = encodeVarintStatusNotifications(dAtA, i, uint64(m.ConnectorId))
		i--
		dAtA[i] = 0x18
	}
	if m.ChargePointId != 0 {
		i = encodeVarintStatusNotifications(dAtA, i, uint64(m.ChargePointId))
		i--
		dAtA[i] = 0x10
	}
	if m.ApplicationId != 0 {
		i = encodeVarintStatusNotifications(dAtA, i, uint64(m.ApplicationId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CreateStatusNotificationResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateStatusNotificationResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateStatusNotificationResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.StatusNotification != nil {
		{
			size, err := m.StatusNotification.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStatusNotifications(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintStatusNotifications(dAtA []byte, offset int, v uint64) int {
	offset -= sovStatusNotifications(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StatusNotification) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovStatusNotifications(uint64(m.Id))
	}
	if m.ChargePointId != 0 {
		n += 1 + sovStatusNotifications(uint64(m.ChargePointId))
	}
	if m.ConnectorId != 0 {
		n += 1 + sovStatusNotifications(uint64(m.ConnectorId))
	}
	l = len(m.ErrorCode)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	l = len(m.Info)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	l = len(m.VendorId)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	l = len(m.VendorErrorCode)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	l = len(m.Timestamp)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	l = len(m.ReportedTimestamp)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetLatestStatusNotificationsReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ApplicationId != 0 {
		n += 1 + sovStatusNotifications(uint64(m.ApplicationId))
	}
	l = len(m.ChargePointIdentifier)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetLatestStatusNotificationsResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ConnectorStatus) > 0 {
		for _, e := range m.ConnectorStatus {
			l = e.Size()
			n += 1 + l + sovStatusNotifications(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *CreateStatusNotificationReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ApplicationId != 0 {
		n += 1 + sovStatusNotifications(uint64(m.ApplicationId))
	}
	if m.ChargePointId != 0 {
		n += 1 + sovStatusNotifications(uint64(m.ChargePointId))
	}
	if m.ConnectorId != 0 {
		n += 1 + sovStatusNotifications(uint64(m.ConnectorId))
	}
	l = len(m.ErrorCode)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	l = len(m.Info)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	l = len(m.Timestamp)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	l = len(m.VendorId)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	l = len(m.VendorErrorCode)
	if l > 0 {
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *CreateStatusNotificationResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StatusNotification != nil {
		l = m.StatusNotification.Size()
		n += 1 + l + sovStatusNotifications(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovStatusNotifications(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStatusNotifications(x uint64) (n int) {
	return sovStatusNotifications(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StatusNotification) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStatusNotifications
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StatusNotification: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StatusNotification: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChargePointId", wireType)
			}
			m.ChargePointId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChargePointId |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectorId", wireType)
			}
			m.ConnectorId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConnectorId |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrorCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Info = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VendorId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VendorId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VendorErrorCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VendorErrorCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Timestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReportedTimestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReportedTimestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStatusNotifications(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLatestStatusNotificationsReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStatusNotifications
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLatestStatusNotificationsReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLatestStatusNotificationsReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApplicationId", wireType)
			}
			m.ApplicationId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ApplicationId |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChargePointIdentifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChargePointIdentifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStatusNotifications(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLatestStatusNotificationsResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStatusNotifications
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLatestStatusNotificationsResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLatestStatusNotificationsResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectorStatus", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConnectorStatus = append(m.ConnectorStatus, &StatusNotification{})
			if err := m.ConnectorStatus[len(m.ConnectorStatus)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStatusNotifications(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateStatusNotificationReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStatusNotifications
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateStatusNotificationReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateStatusNotificationReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApplicationId", wireType)
			}
			m.ApplicationId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ApplicationId |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChargePointId", wireType)
			}
			m.ChargePointId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChargePointId |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectorId", wireType)
			}
			m.ConnectorId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConnectorId |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrorCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Info = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Timestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VendorId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VendorId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VendorErrorCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VendorErrorCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStatusNotifications(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateStatusNotificationResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStatusNotifications
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateStatusNotificationResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateStatusNotificationResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusNotification", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StatusNotification == nil {
				m.StatusNotification = &StatusNotification{}
			}
			if err := m.StatusNotification.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStatusNotifications(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStatusNotifications
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStatusNotifications(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStatusNotifications
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStatusNotifications
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStatusNotifications
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStatusNotifications
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStatusNotifications
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStatusNotifications        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStatusNotifications          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStatusNotifications = fmt.Errorf("proto: unexpected end of group")
)
