basePath: /v2
definitions:
  rpc.RemoteStartTransactionReq:
    properties:
      connector_id:
        type: integer
      cp_id:
        type: string
    type: object
  rpc.RemoteStartTransactionResp:
    type: object
  rpc.RemoteStopTransactionReq:
    properties:
      cp_id:
        type: string
      transaction_id:
        type: integer
    type: object
  rpc.RemoteStopTransactionResp:
    type: object
host: dev.beepbeep.tech
info:
  contact:
    email: lowen@beepbeep.tech
    name: Lowen
  description: Service to interface with OCPP-compliant charge points
  title: BB3 OCPP API
  version: "2.0"
paths:
  /ocpp/operations/remote-start-transaction:
    post:
      consumes:
      - application/json
      parameters:
      - description: Post RemoteStartTransactionReq body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/rpc.RemoteStartTransactionReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rpc.RemoteStartTransactionResp'
      summary: Request Charge Point to Start a Transaction
      tags:
      - Operations
  /ocpp/operations/remote-stop-transaction:
    post:
      consumes:
      - application/json
      parameters:
      - description: Post RemoteStopTransactionReq body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/rpc.RemoteStopTransactionReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rpc.RemoteStopTransactionResp'
      summary: Request Charge Point to Stop a Transaction
      tags:
      - Operations
schemes:
- https
swagger: "2.0"
