definitions:
  rpc.ChargePoint:
    properties:
      charge_box_serial_number:
        type: string
      charge_point_identifier:
        type: string
      charge_point_model:
        type: string
      charge_point_serial_number:
        type: string
      charge_point_vendor:
        type: string
      connector_count:
        type: integer
      entity_code:
        type: string
      firmware_version:
        type: string
      iccid:
        type: string
      id:
        type: integer
      imsi:
        type: string
      meter_serial_number:
        type: string
      meter_type:
        type: string
      ocpp_protocol:
        type: string
    type: object
  rpc.GetChargePointResp:
    properties:
      charge_point:
        $ref: '#/definitions/rpc.ChargePoint'
    type: object
  rpc.GetLatestStatusNotificationsResp:
    properties:
      connector_status:
        items:
          $ref: '#/definitions/rpc.StatusNotification'
        type: array
    type: object
  rpc.RemoteStartTransactionReq:
    properties:
      charge_point_identifier:
        type: string
      connector_id:
        type: integer
      entity_code:
        type: string
    type: object
  rpc.RemoteStartTransactionResp:
    properties:
      transaction_id:
        type: integer
    type: object
  rpc.RemoteStopTransactionReq:
    properties:
      charge_point_identifier:
        type: string
      connector_id:
        type: integer
      entity_code:
        type: string
    type: object
  rpc.RemoteStopTransactionResp:
    type: object
  rpc.StatusNotification:
    properties:
      connector_id:
        type: integer
      error_code:
        type: string
      id:
        type: integer
      info:
        type: string
      reported_timestamp:
        type: string
      status:
        type: string
      timestamp:
        type: string
      vendor_error_code:
        type: string
      vendor_id:
        type: string
    type: object
host: ocpp-dev.chargegowhere.sg:8060
info:
  contact:
    email: lowen@beepbeep.tech
    name: Lowen
  description: Service to interface with OCPP-compliant charge points
  title: BB3 OCPP API
  version: "2.0"
paths:
  /v2/ocpp/charge-points/{entityCode}/{chargePointIdentifier}:
    get:
      parameters:
      - description: entity code
        in: path
        name: entityCode
        required: true
        type: string
      - description: charge point identifier
        in: path
        name: chargePointIdentifier
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rpc.GetChargePointResp'
      summary: Get charge point
      tags:
      - Charge Points
  /v2/ocpp/charge-points/{entityCode}/{chargePointIdentifier}/status:
    get:
      parameters:
      - description: entity code
        in: path
        name: entityCode
        required: true
        type: string
      - description: charge point identifier
        in: path
        name: chargePointIdentifier
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rpc.GetLatestStatusNotificationsResp'
      summary: Get charge point connector status
      tags:
      - Charge Points
  /v2/ocpp/operations/remote-start-transaction:
    post:
      consumes:
      - application/json
      parameters:
      - description: Post RemoteStartTransactionReq body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/rpc.RemoteStartTransactionReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rpc.RemoteStartTransactionResp'
      summary: Request Charge Point to Start a Transaction
      tags:
      - Operations
  /v2/ocpp/operations/remote-stop-transaction:
    post:
      consumes:
      - application/json
      parameters:
      - description: Post RemoteStopTransactionReq body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/rpc.RemoteStopTransactionReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rpc.RemoteStopTransactionResp'
      summary: Request Charge Point to Stop a Transaction
      tags:
      - Operations
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
